name: 'Generate Supabase Database types'
author: 'Estee Tey'
description: 'Automatically updates your type definitions to match your table schemas'

inputs:
  SUPABASE_REF_ID:
    description: "Reference id of your Supabase project"
    required: true
  DB_PASSWORD:
    description: "Database password"
    required: true
  OUTPUT_PATH:
    description: "Path where you want the definitions file to be saved. Any changes will be committed and override existing definition files. Default value is 'src/types/supabase.ts'"
    required: false
    default: "src/types/supabase.ts"

runs:
  using: composite
  steps:
    - name: Checkout project
      uses: actions/checkout@v2
      with:
        persist-credentials: true
        fetch-depth: 0
    - name: Set up supabase cli
      uses: supabase/setup-cli@v1
      with:
        version: 1.4.6
      run: supabase init
    - name: "Generate database typescript types"
      shell: bash
      env:
        SUPABASE_REF_ID: ${{ inputs.SUPABASE_REF_ID }}
        DB_PASSWORD: ${{ inputs.DB_PASSWORD }}
        OUTPUT_PATH: ${{ inputs.OUTPUT_PATH }}
      run: supabase gen types typescript --db-url 'postgresql://postgres:${DB_PASSWORD}@db.${SUPABASE_REF_ID}.supabase.co:5432/postgres' > ${OUTPUT_PATH}
    - name: Check for file changes & commit files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: ${{ inputs.OUTPUT_PATH }}
        commit_message: Update database types
        commit_user_name: Supabot
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: Supabot <41898282+github-actions[bot]@users.noreply.github.com>
        branch: supabot/update-database-types
        create_branch: true
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ github.token }}
        source_branch: supabot/update-database-types
        destination_branch: "main"
        pr_allow_empty: false
        pr_title: '[Supabot] Update database type definitions'
        pr_body: |
          - Auto-generated by [Supabot](https://github.com/lyqht/generate-supabase-db-types-github-action)

branding:
  icon: 'activity'
  color: 'blue'